### ISSUE TITLE
Errors and freezes

### ISSUE THREAD

**Issue by oMqngo** [ezio416/tm-music-control#10]
![Music_Control_error_LOG2](https://github.com/ezio416/tm-music-control/assets/96183399/051ee3d9-e671-46d8-99cb-df840fcabd42)
![Music_Control_error2](https://github.com/ezio416/tm-music-control/assets/96183399/84e42d98-5572-4714-bed9-cbb68d0cd4ff)
![Music_Control_error_LOG](https://github.com/ezio416/tm-music-control/assets/96183399/db10dc4e-a225-44cb-aa45-f545a0ba482b)
![Music_Control_error](https://github.com/ezio416/tm-music-control/assets/96183399/f7b62365-053b-4961-89ca-141658042ff1)

Hello,

When having used the plugin for a while, it keeps showing these error messages several times at once on screen and asks me to look at the log. 
Ive also had the plugin freeze completely (which also froze my entire game).

Kind regards
oMqngo

**Comment by ezio416** [comment]
Thanks for the report! I will better handle this and probably add settings to show fewer warnings

**Comment by oMqngo** [comment]
oh i also forgot to ask: when skipping songs, it takes quite a while to display the right things. Is this "issue" plugin sided or spotify services sided?

**Comment by ezio416** [comment]
Issues should mostly be resolved with the next released version (0.3.0). I've added a setting to hide all on-screen error messages, improved loading album art, disabled loading album art when set to not even show it, and improved the logic behind fetching data from the API - greatly reducing the number of error messages in general.

I will close this when the next version is approved & released. Feel free to open again if issues persist.
