### ISSUE TITLE
Heart

### ISSUE THREAD

**Issue by donnelic** [ezio416/tm-music-control#21]
A cool idea would be to add a like button, if that were to be possible. Only thing, appart from scrolling names, which i am missing, great plugin.

**Comment by ezio416** [comment]
Yes this is possible, however I'm very hesitant to grant permissions to modify your library as the keys the plugin uses to read/control playback are not secured in any way. I guess I could somehow make it an opt-in thing for people who want to take that risk. I will think about it

**Comment by ezio416** [comment]
https://developer.spotify.com/documentation/web-api/reference/check-users-saved-tracks

**Comment by ezio416** [comment]
checking if a song is in a user's library will be in the next update, though I still won't allow adding/removing liked songs
